<?php
/**
 * AccountAnalytics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * AccountAnalytics Class Doc Comment
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountAnalytics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountAnalytics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'applications' => 'int',
        'liveApplications' => 'int',
        'sandboxApplications' => 'int',
        'campaigns' => 'int',
        'activeCampaigns' => 'int',
        'liveActiveCampaigns' => 'int',
        'coupons' => 'int',
        'activeCoupons' => 'int',
        'expiredCoupons' => 'int',
        'referralCodes' => 'int',
        'activeReferralCodes' => 'int',
        'expiredReferralCodes' => 'int',
        'activeRules' => 'int',
        'users' => 'int',
        'roles' => 'int',
        'customAttributes' => 'int',
        'webhooks' => 'int',
        'loyaltyPrograms' => 'int',
        'liveLoyaltyPrograms' => 'int',
        'lastUpdatedAt' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'applications' => 'int64',
        'liveApplications' => 'int64',
        'sandboxApplications' => 'int64',
        'campaigns' => 'int64',
        'activeCampaigns' => 'int64',
        'liveActiveCampaigns' => 'int64',
        'coupons' => 'int64',
        'activeCoupons' => 'int64',
        'expiredCoupons' => 'int64',
        'referralCodes' => 'int64',
        'activeReferralCodes' => 'int64',
        'expiredReferralCodes' => 'int64',
        'activeRules' => 'int64',
        'users' => 'int64',
        'roles' => 'int64',
        'customAttributes' => 'int64',
        'webhooks' => 'int64',
        'loyaltyPrograms' => 'int64',
        'liveLoyaltyPrograms' => 'int64',
        'lastUpdatedAt' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'applications' => false,
        'liveApplications' => false,
        'sandboxApplications' => false,
        'campaigns' => false,
        'activeCampaigns' => false,
        'liveActiveCampaigns' => false,
        'coupons' => false,
        'activeCoupons' => false,
        'expiredCoupons' => false,
        'referralCodes' => false,
        'activeReferralCodes' => false,
        'expiredReferralCodes' => false,
        'activeRules' => false,
        'users' => false,
        'roles' => false,
        'customAttributes' => false,
        'webhooks' => false,
        'loyaltyPrograms' => false,
        'liveLoyaltyPrograms' => false,
        'lastUpdatedAt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'applications' => 'applications',
        'liveApplications' => 'liveApplications',
        'sandboxApplications' => 'sandboxApplications',
        'campaigns' => 'campaigns',
        'activeCampaigns' => 'activeCampaigns',
        'liveActiveCampaigns' => 'liveActiveCampaigns',
        'coupons' => 'coupons',
        'activeCoupons' => 'activeCoupons',
        'expiredCoupons' => 'expiredCoupons',
        'referralCodes' => 'referralCodes',
        'activeReferralCodes' => 'activeReferralCodes',
        'expiredReferralCodes' => 'expiredReferralCodes',
        'activeRules' => 'activeRules',
        'users' => 'users',
        'roles' => 'roles',
        'customAttributes' => 'customAttributes',
        'webhooks' => 'webhooks',
        'loyaltyPrograms' => 'loyaltyPrograms',
        'liveLoyaltyPrograms' => 'liveLoyaltyPrograms',
        'lastUpdatedAt' => 'lastUpdatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'applications' => 'setApplications',
        'liveApplications' => 'setLiveApplications',
        'sandboxApplications' => 'setSandboxApplications',
        'campaigns' => 'setCampaigns',
        'activeCampaigns' => 'setActiveCampaigns',
        'liveActiveCampaigns' => 'setLiveActiveCampaigns',
        'coupons' => 'setCoupons',
        'activeCoupons' => 'setActiveCoupons',
        'expiredCoupons' => 'setExpiredCoupons',
        'referralCodes' => 'setReferralCodes',
        'activeReferralCodes' => 'setActiveReferralCodes',
        'expiredReferralCodes' => 'setExpiredReferralCodes',
        'activeRules' => 'setActiveRules',
        'users' => 'setUsers',
        'roles' => 'setRoles',
        'customAttributes' => 'setCustomAttributes',
        'webhooks' => 'setWebhooks',
        'loyaltyPrograms' => 'setLoyaltyPrograms',
        'liveLoyaltyPrograms' => 'setLiveLoyaltyPrograms',
        'lastUpdatedAt' => 'setLastUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'applications' => 'getApplications',
        'liveApplications' => 'getLiveApplications',
        'sandboxApplications' => 'getSandboxApplications',
        'campaigns' => 'getCampaigns',
        'activeCampaigns' => 'getActiveCampaigns',
        'liveActiveCampaigns' => 'getLiveActiveCampaigns',
        'coupons' => 'getCoupons',
        'activeCoupons' => 'getActiveCoupons',
        'expiredCoupons' => 'getExpiredCoupons',
        'referralCodes' => 'getReferralCodes',
        'activeReferralCodes' => 'getActiveReferralCodes',
        'expiredReferralCodes' => 'getExpiredReferralCodes',
        'activeRules' => 'getActiveRules',
        'users' => 'getUsers',
        'roles' => 'getRoles',
        'customAttributes' => 'getCustomAttributes',
        'webhooks' => 'getWebhooks',
        'loyaltyPrograms' => 'getLoyaltyPrograms',
        'liveLoyaltyPrograms' => 'getLiveLoyaltyPrograms',
        'lastUpdatedAt' => 'getLastUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('applications', $data ?? [], null);
        $this->setIfExists('liveApplications', $data ?? [], null);
        $this->setIfExists('sandboxApplications', $data ?? [], null);
        $this->setIfExists('campaigns', $data ?? [], null);
        $this->setIfExists('activeCampaigns', $data ?? [], null);
        $this->setIfExists('liveActiveCampaigns', $data ?? [], null);
        $this->setIfExists('coupons', $data ?? [], null);
        $this->setIfExists('activeCoupons', $data ?? [], null);
        $this->setIfExists('expiredCoupons', $data ?? [], null);
        $this->setIfExists('referralCodes', $data ?? [], null);
        $this->setIfExists('activeReferralCodes', $data ?? [], null);
        $this->setIfExists('expiredReferralCodes', $data ?? [], null);
        $this->setIfExists('activeRules', $data ?? [], null);
        $this->setIfExists('users', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('customAttributes', $data ?? [], null);
        $this->setIfExists('webhooks', $data ?? [], null);
        $this->setIfExists('loyaltyPrograms', $data ?? [], null);
        $this->setIfExists('liveLoyaltyPrograms', $data ?? [], null);
        $this->setIfExists('lastUpdatedAt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['applications'] === null) {
            $invalidProperties[] = "'applications' can't be null";
        }
        if ($this->container['liveApplications'] === null) {
            $invalidProperties[] = "'liveApplications' can't be null";
        }
        if ($this->container['sandboxApplications'] === null) {
            $invalidProperties[] = "'sandboxApplications' can't be null";
        }
        if ($this->container['campaigns'] === null) {
            $invalidProperties[] = "'campaigns' can't be null";
        }
        if ($this->container['activeCampaigns'] === null) {
            $invalidProperties[] = "'activeCampaigns' can't be null";
        }
        if ($this->container['liveActiveCampaigns'] === null) {
            $invalidProperties[] = "'liveActiveCampaigns' can't be null";
        }
        if ($this->container['coupons'] === null) {
            $invalidProperties[] = "'coupons' can't be null";
        }
        if ($this->container['activeCoupons'] === null) {
            $invalidProperties[] = "'activeCoupons' can't be null";
        }
        if ($this->container['expiredCoupons'] === null) {
            $invalidProperties[] = "'expiredCoupons' can't be null";
        }
        if ($this->container['referralCodes'] === null) {
            $invalidProperties[] = "'referralCodes' can't be null";
        }
        if ($this->container['activeReferralCodes'] === null) {
            $invalidProperties[] = "'activeReferralCodes' can't be null";
        }
        if ($this->container['expiredReferralCodes'] === null) {
            $invalidProperties[] = "'expiredReferralCodes' can't be null";
        }
        if ($this->container['activeRules'] === null) {
            $invalidProperties[] = "'activeRules' can't be null";
        }
        if ($this->container['users'] === null) {
            $invalidProperties[] = "'users' can't be null";
        }
        if ($this->container['roles'] === null) {
            $invalidProperties[] = "'roles' can't be null";
        }
        if ($this->container['customAttributes'] === null) {
            $invalidProperties[] = "'customAttributes' can't be null";
        }
        if ($this->container['webhooks'] === null) {
            $invalidProperties[] = "'webhooks' can't be null";
        }
        if ($this->container['loyaltyPrograms'] === null) {
            $invalidProperties[] = "'loyaltyPrograms' can't be null";
        }
        if ($this->container['liveLoyaltyPrograms'] === null) {
            $invalidProperties[] = "'liveLoyaltyPrograms' can't be null";
        }
        if ($this->container['lastUpdatedAt'] === null) {
            $invalidProperties[] = "'lastUpdatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets applications
     *
     * @return int
     */
    public function getApplications()
    {
        return $this->container['applications'];
    }

    /**
     * Sets applications
     *
     * @param int $applications Total number of applications in the account.
     *
     * @return self
     */
    public function setApplications($applications)
    {
        if (is_null($applications)) {
            throw new \InvalidArgumentException('non-nullable applications cannot be null');
        }
        $this->container['applications'] = $applications;

        return $this;
    }

    /**
     * Gets liveApplications
     *
     * @return int
     */
    public function getLiveApplications()
    {
        return $this->container['liveApplications'];
    }

    /**
     * Sets liveApplications
     *
     * @param int $liveApplications Total number of live applications in the account.
     *
     * @return self
     */
    public function setLiveApplications($liveApplications)
    {
        if (is_null($liveApplications)) {
            throw new \InvalidArgumentException('non-nullable liveApplications cannot be null');
        }
        $this->container['liveApplications'] = $liveApplications;

        return $this;
    }

    /**
     * Gets sandboxApplications
     *
     * @return int
     */
    public function getSandboxApplications()
    {
        return $this->container['sandboxApplications'];
    }

    /**
     * Sets sandboxApplications
     *
     * @param int $sandboxApplications Total number of sandbox applications in the account.
     *
     * @return self
     */
    public function setSandboxApplications($sandboxApplications)
    {
        if (is_null($sandboxApplications)) {
            throw new \InvalidArgumentException('non-nullable sandboxApplications cannot be null');
        }
        $this->container['sandboxApplications'] = $sandboxApplications;

        return $this;
    }

    /**
     * Gets campaigns
     *
     * @return int
     */
    public function getCampaigns()
    {
        return $this->container['campaigns'];
    }

    /**
     * Sets campaigns
     *
     * @param int $campaigns Total number of campaigns in the account.
     *
     * @return self
     */
    public function setCampaigns($campaigns)
    {
        if (is_null($campaigns)) {
            throw new \InvalidArgumentException('non-nullable campaigns cannot be null');
        }
        $this->container['campaigns'] = $campaigns;

        return $this;
    }

    /**
     * Gets activeCampaigns
     *
     * @return int
     */
    public function getActiveCampaigns()
    {
        return $this->container['activeCampaigns'];
    }

    /**
     * Sets activeCampaigns
     *
     * @param int $activeCampaigns Total number of active campaigns in the account.
     *
     * @return self
     */
    public function setActiveCampaigns($activeCampaigns)
    {
        if (is_null($activeCampaigns)) {
            throw new \InvalidArgumentException('non-nullable activeCampaigns cannot be null');
        }
        $this->container['activeCampaigns'] = $activeCampaigns;

        return $this;
    }

    /**
     * Gets liveActiveCampaigns
     *
     * @return int
     */
    public function getLiveActiveCampaigns()
    {
        return $this->container['liveActiveCampaigns'];
    }

    /**
     * Sets liveActiveCampaigns
     *
     * @param int $liveActiveCampaigns Total number of active campaigns in live applications in the account.
     *
     * @return self
     */
    public function setLiveActiveCampaigns($liveActiveCampaigns)
    {
        if (is_null($liveActiveCampaigns)) {
            throw new \InvalidArgumentException('non-nullable liveActiveCampaigns cannot be null');
        }
        $this->container['liveActiveCampaigns'] = $liveActiveCampaigns;

        return $this;
    }

    /**
     * Gets coupons
     *
     * @return int
     */
    public function getCoupons()
    {
        return $this->container['coupons'];
    }

    /**
     * Sets coupons
     *
     * @param int $coupons Total number of coupons in the account.
     *
     * @return self
     */
    public function setCoupons($coupons)
    {
        if (is_null($coupons)) {
            throw new \InvalidArgumentException('non-nullable coupons cannot be null');
        }
        $this->container['coupons'] = $coupons;

        return $this;
    }

    /**
     * Gets activeCoupons
     *
     * @return int
     */
    public function getActiveCoupons()
    {
        return $this->container['activeCoupons'];
    }

    /**
     * Sets activeCoupons
     *
     * @param int $activeCoupons Total number of active coupons in the account.
     *
     * @return self
     */
    public function setActiveCoupons($activeCoupons)
    {
        if (is_null($activeCoupons)) {
            throw new \InvalidArgumentException('non-nullable activeCoupons cannot be null');
        }
        $this->container['activeCoupons'] = $activeCoupons;

        return $this;
    }

    /**
     * Gets expiredCoupons
     *
     * @return int
     */
    public function getExpiredCoupons()
    {
        return $this->container['expiredCoupons'];
    }

    /**
     * Sets expiredCoupons
     *
     * @param int $expiredCoupons Total number of expired coupons in the account.
     *
     * @return self
     */
    public function setExpiredCoupons($expiredCoupons)
    {
        if (is_null($expiredCoupons)) {
            throw new \InvalidArgumentException('non-nullable expiredCoupons cannot be null');
        }
        $this->container['expiredCoupons'] = $expiredCoupons;

        return $this;
    }

    /**
     * Gets referralCodes
     *
     * @return int
     */
    public function getReferralCodes()
    {
        return $this->container['referralCodes'];
    }

    /**
     * Sets referralCodes
     *
     * @param int $referralCodes Total number of referral codes in the account.
     *
     * @return self
     */
    public function setReferralCodes($referralCodes)
    {
        if (is_null($referralCodes)) {
            throw new \InvalidArgumentException('non-nullable referralCodes cannot be null');
        }
        $this->container['referralCodes'] = $referralCodes;

        return $this;
    }

    /**
     * Gets activeReferralCodes
     *
     * @return int
     */
    public function getActiveReferralCodes()
    {
        return $this->container['activeReferralCodes'];
    }

    /**
     * Sets activeReferralCodes
     *
     * @param int $activeReferralCodes Total number of active referral codes in the account.
     *
     * @return self
     */
    public function setActiveReferralCodes($activeReferralCodes)
    {
        if (is_null($activeReferralCodes)) {
            throw new \InvalidArgumentException('non-nullable activeReferralCodes cannot be null');
        }
        $this->container['activeReferralCodes'] = $activeReferralCodes;

        return $this;
    }

    /**
     * Gets expiredReferralCodes
     *
     * @return int
     */
    public function getExpiredReferralCodes()
    {
        return $this->container['expiredReferralCodes'];
    }

    /**
     * Sets expiredReferralCodes
     *
     * @param int $expiredReferralCodes Total number of expired referral codes in the account.
     *
     * @return self
     */
    public function setExpiredReferralCodes($expiredReferralCodes)
    {
        if (is_null($expiredReferralCodes)) {
            throw new \InvalidArgumentException('non-nullable expiredReferralCodes cannot be null');
        }
        $this->container['expiredReferralCodes'] = $expiredReferralCodes;

        return $this;
    }

    /**
     * Gets activeRules
     *
     * @return int
     */
    public function getActiveRules()
    {
        return $this->container['activeRules'];
    }

    /**
     * Sets activeRules
     *
     * @param int $activeRules Total number of active rules in the account.
     *
     * @return self
     */
    public function setActiveRules($activeRules)
    {
        if (is_null($activeRules)) {
            throw new \InvalidArgumentException('non-nullable activeRules cannot be null');
        }
        $this->container['activeRules'] = $activeRules;

        return $this;
    }

    /**
     * Gets users
     *
     * @return int
     */
    public function getUsers()
    {
        return $this->container['users'];
    }

    /**
     * Sets users
     *
     * @param int $users Total number of users in the account.
     *
     * @return self
     */
    public function setUsers($users)
    {
        if (is_null($users)) {
            throw new \InvalidArgumentException('non-nullable users cannot be null');
        }
        $this->container['users'] = $users;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return int
     */
    public function getRoles()
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param int $roles Total number of roles in the account.
     *
     * @return self
     */
    public function setRoles($roles)
    {
        if (is_null($roles)) {
            throw new \InvalidArgumentException('non-nullable roles cannot be null');
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets customAttributes
     *
     * @return int
     */
    public function getCustomAttributes()
    {
        return $this->container['customAttributes'];
    }

    /**
     * Sets customAttributes
     *
     * @param int $customAttributes Total number of custom attributes in the account.
     *
     * @return self
     */
    public function setCustomAttributes($customAttributes)
    {
        if (is_null($customAttributes)) {
            throw new \InvalidArgumentException('non-nullable customAttributes cannot be null');
        }
        $this->container['customAttributes'] = $customAttributes;

        return $this;
    }

    /**
     * Gets webhooks
     *
     * @return int
     */
    public function getWebhooks()
    {
        return $this->container['webhooks'];
    }

    /**
     * Sets webhooks
     *
     * @param int $webhooks Total number of webhooks in the account.
     *
     * @return self
     */
    public function setWebhooks($webhooks)
    {
        if (is_null($webhooks)) {
            throw new \InvalidArgumentException('non-nullable webhooks cannot be null');
        }
        $this->container['webhooks'] = $webhooks;

        return $this;
    }

    /**
     * Gets loyaltyPrograms
     *
     * @return int
     */
    public function getLoyaltyPrograms()
    {
        return $this->container['loyaltyPrograms'];
    }

    /**
     * Sets loyaltyPrograms
     *
     * @param int $loyaltyPrograms Total number of all loyalty programs in the account.
     *
     * @return self
     */
    public function setLoyaltyPrograms($loyaltyPrograms)
    {
        if (is_null($loyaltyPrograms)) {
            throw new \InvalidArgumentException('non-nullable loyaltyPrograms cannot be null');
        }
        $this->container['loyaltyPrograms'] = $loyaltyPrograms;

        return $this;
    }

    /**
     * Gets liveLoyaltyPrograms
     *
     * @return int
     */
    public function getLiveLoyaltyPrograms()
    {
        return $this->container['liveLoyaltyPrograms'];
    }

    /**
     * Sets liveLoyaltyPrograms
     *
     * @param int $liveLoyaltyPrograms Total number of live loyalty programs in the account.
     *
     * @return self
     */
    public function setLiveLoyaltyPrograms($liveLoyaltyPrograms)
    {
        if (is_null($liveLoyaltyPrograms)) {
            throw new \InvalidArgumentException('non-nullable liveLoyaltyPrograms cannot be null');
        }
        $this->container['liveLoyaltyPrograms'] = $liveLoyaltyPrograms;

        return $this;
    }

    /**
     * Gets lastUpdatedAt
     *
     * @return \DateTime
     */
    public function getLastUpdatedAt()
    {
        return $this->container['lastUpdatedAt'];
    }

    /**
     * Sets lastUpdatedAt
     *
     * @param \DateTime $lastUpdatedAt The point in time when the analytics numbers were updated last.
     *
     * @return self
     */
    public function setLastUpdatedAt($lastUpdatedAt)
    {
        if (is_null($lastUpdatedAt)) {
            throw new \InvalidArgumentException('non-nullable lastUpdatedAt cannot be null');
        }
        $this->container['lastUpdatedAt'] = $lastUpdatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


