<?php
/**
 * AchievementProgressWithDefinition
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * AchievementProgressWithDefinition Class Doc Comment
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AchievementProgressWithDefinition implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AchievementProgressWithDefinition';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'status' => 'string',
        'progress' => 'float',
        'startDate' => '\DateTime',
        'completionDate' => '\DateTime',
        'endDate' => '\DateTime',
        'achievementId' => 'int',
        'name' => 'string',
        'title' => 'string',
        'description' => 'string',
        'campaignId' => 'int',
        'target' => 'float',
        'achievementRecurrencePolicy' => 'string',
        'achievementActivationPolicy' => 'string',
        'achievementFixedStartDate' => '\DateTime',
        'achievementEndDate' => '\DateTime',
        'achievementAllowRollbackAfterCompletion' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'status' => null,
        'progress' => null,
        'startDate' => 'date-time',
        'completionDate' => 'date-time',
        'endDate' => 'date-time',
        'achievementId' => 'int64',
        'name' => null,
        'title' => null,
        'description' => 'string',
        'campaignId' => 'int64',
        'target' => null,
        'achievementRecurrencePolicy' => null,
        'achievementActivationPolicy' => null,
        'achievementFixedStartDate' => 'date-time',
        'achievementEndDate' => 'date-time',
        'achievementAllowRollbackAfterCompletion' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'status' => false,
        'progress' => false,
        'startDate' => false,
        'completionDate' => false,
        'endDate' => false,
        'achievementId' => false,
        'name' => false,
        'title' => false,
        'description' => false,
        'campaignId' => false,
        'target' => false,
        'achievementRecurrencePolicy' => false,
        'achievementActivationPolicy' => false,
        'achievementFixedStartDate' => false,
        'achievementEndDate' => false,
        'achievementAllowRollbackAfterCompletion' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'status' => 'status',
        'progress' => 'progress',
        'startDate' => 'startDate',
        'completionDate' => 'completionDate',
        'endDate' => 'endDate',
        'achievementId' => 'achievementId',
        'name' => 'name',
        'title' => 'title',
        'description' => 'description',
        'campaignId' => 'campaignId',
        'target' => 'target',
        'achievementRecurrencePolicy' => 'achievementRecurrencePolicy',
        'achievementActivationPolicy' => 'achievementActivationPolicy',
        'achievementFixedStartDate' => 'achievementFixedStartDate',
        'achievementEndDate' => 'achievementEndDate',
        'achievementAllowRollbackAfterCompletion' => 'achievementAllowRollbackAfterCompletion'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'status' => 'setStatus',
        'progress' => 'setProgress',
        'startDate' => 'setStartDate',
        'completionDate' => 'setCompletionDate',
        'endDate' => 'setEndDate',
        'achievementId' => 'setAchievementId',
        'name' => 'setName',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'campaignId' => 'setCampaignId',
        'target' => 'setTarget',
        'achievementRecurrencePolicy' => 'setAchievementRecurrencePolicy',
        'achievementActivationPolicy' => 'setAchievementActivationPolicy',
        'achievementFixedStartDate' => 'setAchievementFixedStartDate',
        'achievementEndDate' => 'setAchievementEndDate',
        'achievementAllowRollbackAfterCompletion' => 'setAchievementAllowRollbackAfterCompletion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'status' => 'getStatus',
        'progress' => 'getProgress',
        'startDate' => 'getStartDate',
        'completionDate' => 'getCompletionDate',
        'endDate' => 'getEndDate',
        'achievementId' => 'getAchievementId',
        'name' => 'getName',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'campaignId' => 'getCampaignId',
        'target' => 'getTarget',
        'achievementRecurrencePolicy' => 'getAchievementRecurrencePolicy',
        'achievementActivationPolicy' => 'getAchievementActivationPolicy',
        'achievementFixedStartDate' => 'getAchievementFixedStartDate',
        'achievementEndDate' => 'getAchievementEndDate',
        'achievementAllowRollbackAfterCompletion' => 'getAchievementAllowRollbackAfterCompletion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_INPROGRESS = 'inprogress';
    public const STATUS_COMPLETED = 'completed';
    public const STATUS_EXPIRED = 'expired';
    public const STATUS_NOT_STARTED = 'not_started';
    public const ACHIEVEMENT_RECURRENCE_POLICY_NO_RECURRENCE = 'no_recurrence';
    public const ACHIEVEMENT_RECURRENCE_POLICY_ON_EXPIRATION = 'on_expiration';
    public const ACHIEVEMENT_RECURRENCE_POLICY_ON_COMPLETION = 'on_completion';
    public const ACHIEVEMENT_ACTIVATION_POLICY_USER_ACTION = 'user_action';
    public const ACHIEVEMENT_ACTIVATION_POLICY_FIXED_SCHEDULE = 'fixed_schedule';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_INPROGRESS,
            self::STATUS_COMPLETED,
            self::STATUS_EXPIRED,
            self::STATUS_NOT_STARTED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAchievementRecurrencePolicyAllowableValues()
    {
        return [
            self::ACHIEVEMENT_RECURRENCE_POLICY_NO_RECURRENCE,
            self::ACHIEVEMENT_RECURRENCE_POLICY_ON_EXPIRATION,
            self::ACHIEVEMENT_RECURRENCE_POLICY_ON_COMPLETION,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAchievementActivationPolicyAllowableValues()
    {
        return [
            self::ACHIEVEMENT_ACTIVATION_POLICY_USER_ACTION,
            self::ACHIEVEMENT_ACTIVATION_POLICY_FIXED_SCHEDULE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('progress', $data ?? [], null);
        $this->setIfExists('startDate', $data ?? [], null);
        $this->setIfExists('completionDate', $data ?? [], null);
        $this->setIfExists('endDate', $data ?? [], null);
        $this->setIfExists('achievementId', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('campaignId', $data ?? [], null);
        $this->setIfExists('target', $data ?? [], null);
        $this->setIfExists('achievementRecurrencePolicy', $data ?? [], null);
        $this->setIfExists('achievementActivationPolicy', $data ?? [], null);
        $this->setIfExists('achievementFixedStartDate', $data ?? [], null);
        $this->setIfExists('achievementEndDate', $data ?? [], null);
        $this->setIfExists('achievementAllowRollbackAfterCompletion', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['progress'] === null) {
            $invalidProperties[] = "'progress' can't be null";
        }
        if ($this->container['achievementId'] === null) {
            $invalidProperties[] = "'achievementId' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 1000)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 1000.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[a-zA-Z]\\w+$/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /^[a-zA-Z]\\w+$/.";
        }

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['campaignId'] === null) {
            $invalidProperties[] = "'campaignId' can't be null";
        }
        if ($this->container['achievementRecurrencePolicy'] === null) {
            $invalidProperties[] = "'achievementRecurrencePolicy' can't be null";
        }
        $allowedValues = $this->getAchievementRecurrencePolicyAllowableValues();
        if (!is_null($this->container['achievementRecurrencePolicy']) && !in_array($this->container['achievementRecurrencePolicy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'achievementRecurrencePolicy', must be one of '%s'",
                $this->container['achievementRecurrencePolicy'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['achievementActivationPolicy'] === null) {
            $invalidProperties[] = "'achievementActivationPolicy' can't be null";
        }
        $allowedValues = $this->getAchievementActivationPolicyAllowableValues();
        if (!is_null($this->container['achievementActivationPolicy']) && !in_array($this->container['achievementActivationPolicy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'achievementActivationPolicy', must be one of '%s'",
                $this->container['achievementActivationPolicy'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The status of the achievement.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets progress
     *
     * @return float
     */
    public function getProgress()
    {
        return $this->container['progress'];
    }

    /**
     * Sets progress
     *
     * @param float $progress The current progress of the customer in the achievement.
     *
     * @return self
     */
    public function setProgress($progress)
    {
        if (is_null($progress)) {
            throw new \InvalidArgumentException('non-nullable progress cannot be null');
        }
        $this->container['progress'] = $progress;

        return $this;
    }

    /**
     * Gets startDate
     *
     * @return \DateTime|null
     */
    public function getStartDate()
    {
        return $this->container['startDate'];
    }

    /**
     * Sets startDate
     *
     * @param \DateTime|null $startDate Timestamp at which the customer started the achievement.
     *
     * @return self
     */
    public function setStartDate($startDate)
    {
        if (is_null($startDate)) {
            throw new \InvalidArgumentException('non-nullable startDate cannot be null');
        }
        $this->container['startDate'] = $startDate;

        return $this;
    }

    /**
     * Gets completionDate
     *
     * @return \DateTime|null
     */
    public function getCompletionDate()
    {
        return $this->container['completionDate'];
    }

    /**
     * Sets completionDate
     *
     * @param \DateTime|null $completionDate Timestamp at which point the customer completed the achievement.
     *
     * @return self
     */
    public function setCompletionDate($completionDate)
    {
        if (is_null($completionDate)) {
            throw new \InvalidArgumentException('non-nullable completionDate cannot be null');
        }
        $this->container['completionDate'] = $completionDate;

        return $this;
    }

    /**
     * Gets endDate
     *
     * @return \DateTime|null
     */
    public function getEndDate()
    {
        return $this->container['endDate'];
    }

    /**
     * Sets endDate
     *
     * @param \DateTime|null $endDate Timestamp at which point the achievement ends and resets for the customer.
     *
     * @return self
     */
    public function setEndDate($endDate)
    {
        if (is_null($endDate)) {
            throw new \InvalidArgumentException('non-nullable endDate cannot be null');
        }
        $this->container['endDate'] = $endDate;

        return $this;
    }

    /**
     * Gets achievementId
     *
     * @return int
     */
    public function getAchievementId()
    {
        return $this->container['achievementId'];
    }

    /**
     * Sets achievementId
     *
     * @param int $achievementId The internal ID of the achievement.
     *
     * @return self
     */
    public function setAchievementId($achievementId)
    {
        if (is_null($achievementId)) {
            throw new \InvalidArgumentException('non-nullable achievementId cannot be null');
        }
        $this->container['achievementId'] = $achievementId;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The internal name of the achievement used in API requests.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $name when calling AchievementProgressWithDefinition., must be smaller than or equal to 1000.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling AchievementProgressWithDefinition., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[a-zA-Z]\\w+$/", ObjectSerializer::toString($name)))) {
            throw new \InvalidArgumentException("invalid value for \$name when calling AchievementProgressWithDefinition., must conform to the pattern /^[a-zA-Z]\\w+$/.");
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The display name of the achievement in the Campaign Manager.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description The description of the achievement in the Campaign Manager.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets campaignId
     *
     * @return int
     */
    public function getCampaignId()
    {
        return $this->container['campaignId'];
    }

    /**
     * Sets campaignId
     *
     * @param int $campaignId The ID of the campaign the achievement belongs to.
     *
     * @return self
     */
    public function setCampaignId($campaignId)
    {
        if (is_null($campaignId)) {
            throw new \InvalidArgumentException('non-nullable campaignId cannot be null');
        }
        $this->container['campaignId'] = $campaignId;

        return $this;
    }

    /**
     * Gets target
     *
     * @return float|null
     */
    public function getTarget()
    {
        return $this->container['target'];
    }

    /**
     * Sets target
     *
     * @param float|null $target The required number of actions or the transactional milestone to complete the achievement.
     *
     * @return self
     */
    public function setTarget($target)
    {
        if (is_null($target)) {
            throw new \InvalidArgumentException('non-nullable target cannot be null');
        }
        $this->container['target'] = $target;

        return $this;
    }

    /**
     * Gets achievementRecurrencePolicy
     *
     * @return string
     */
    public function getAchievementRecurrencePolicy()
    {
        return $this->container['achievementRecurrencePolicy'];
    }

    /**
     * Sets achievementRecurrencePolicy
     *
     * @param string $achievementRecurrencePolicy The policy that determines if and how the achievement recurs. - `no_recurrence`: The achievement can be completed only once. - `on_expiration`: The achievement resets after it expires and becomes available again. - `on_completion`: When the customer progress status reaches `completed`, the achievement resets and becomes available again.
     *
     * @return self
     */
    public function setAchievementRecurrencePolicy($achievementRecurrencePolicy)
    {
        if (is_null($achievementRecurrencePolicy)) {
            throw new \InvalidArgumentException('non-nullable achievementRecurrencePolicy cannot be null');
        }
        $allowedValues = $this->getAchievementRecurrencePolicyAllowableValues();
        if (!in_array($achievementRecurrencePolicy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'achievementRecurrencePolicy', must be one of '%s'",
                    $achievementRecurrencePolicy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['achievementRecurrencePolicy'] = $achievementRecurrencePolicy;

        return $this;
    }

    /**
     * Gets achievementActivationPolicy
     *
     * @return string
     */
    public function getAchievementActivationPolicy()
    {
        return $this->container['achievementActivationPolicy'];
    }

    /**
     * Sets achievementActivationPolicy
     *
     * @param string $achievementActivationPolicy The policy that determines how the achievement starts, ends, or resets. - `user_action`: The achievement ends or resets relative to when the customer started the achievement. - `fixed_schedule`: The achievement starts, ends, or resets for all customers following a fixed schedule.
     *
     * @return self
     */
    public function setAchievementActivationPolicy($achievementActivationPolicy)
    {
        if (is_null($achievementActivationPolicy)) {
            throw new \InvalidArgumentException('non-nullable achievementActivationPolicy cannot be null');
        }
        $allowedValues = $this->getAchievementActivationPolicyAllowableValues();
        if (!in_array($achievementActivationPolicy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'achievementActivationPolicy', must be one of '%s'",
                    $achievementActivationPolicy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['achievementActivationPolicy'] = $achievementActivationPolicy;

        return $this;
    }

    /**
     * Gets achievementFixedStartDate
     *
     * @return \DateTime|null
     */
    public function getAchievementFixedStartDate()
    {
        return $this->container['achievementFixedStartDate'];
    }

    /**
     * Sets achievementFixedStartDate
     *
     * @param \DateTime|null $achievementFixedStartDate The achievement's start date when `achievementActivationPolicy` is equal to `fixed_schedule`.  **Note:** It is an RFC3339 timestamp string.
     *
     * @return self
     */
    public function setAchievementFixedStartDate($achievementFixedStartDate)
    {
        if (is_null($achievementFixedStartDate)) {
            throw new \InvalidArgumentException('non-nullable achievementFixedStartDate cannot be null');
        }
        $this->container['achievementFixedStartDate'] = $achievementFixedStartDate;

        return $this;
    }

    /**
     * Gets achievementEndDate
     *
     * @return \DateTime|null
     */
    public function getAchievementEndDate()
    {
        return $this->container['achievementEndDate'];
    }

    /**
     * Sets achievementEndDate
     *
     * @param \DateTime|null $achievementEndDate The achievement's end date. If defined, customers cannot participate in the achievement after this date.  **Note:** It is an RFC3339 timestamp string.
     *
     * @return self
     */
    public function setAchievementEndDate($achievementEndDate)
    {
        if (is_null($achievementEndDate)) {
            throw new \InvalidArgumentException('non-nullable achievementEndDate cannot be null');
        }
        $this->container['achievementEndDate'] = $achievementEndDate;

        return $this;
    }

    /**
     * Gets achievementAllowRollbackAfterCompletion
     *
     * @return bool|null
     */
    public function getAchievementAllowRollbackAfterCompletion()
    {
        return $this->container['achievementAllowRollbackAfterCompletion'];
    }

    /**
     * Sets achievementAllowRollbackAfterCompletion
     *
     * @param bool|null $achievementAllowRollbackAfterCompletion When `true`, customer progress can be rolled back in completed achievements.
     *
     * @return self
     */
    public function setAchievementAllowRollbackAfterCompletion($achievementAllowRollbackAfterCompletion)
    {
        if (is_null($achievementAllowRollbackAfterCompletion)) {
            throw new \InvalidArgumentException('non-nullable achievementAllowRollbackAfterCompletion cannot be null');
        }
        $this->container['achievementAllowRollbackAfterCompletion'] = $achievementAllowRollbackAfterCompletion;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


