<?php
/**
 * CouponsNotificationData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * CouponsNotificationData Class Doc Comment
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CouponsNotificationData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CouponsNotificationData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'typeOfChange' => 'string',
        'operation' => 'string',
        'employeeName' => 'string',
        'data' => '\TalonOne\Client\Model\ExtendedCoupon[]',
        'totalResultSize' => 'int',
        'notificationType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'typeOfChange' => null,
        'operation' => null,
        'employeeName' => null,
        'data' => null,
        'totalResultSize' => 'int64',
        'notificationType' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'typeOfChange' => false,
        'operation' => false,
        'employeeName' => false,
        'data' => false,
        'totalResultSize' => false,
        'notificationType' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'typeOfChange' => 'TypeOfChange',
        'operation' => 'Operation',
        'employeeName' => 'EmployeeName',
        'data' => 'data',
        'totalResultSize' => 'totalResultSize',
        'notificationType' => 'NotificationType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'typeOfChange' => 'setTypeOfChange',
        'operation' => 'setOperation',
        'employeeName' => 'setEmployeeName',
        'data' => 'setData',
        'totalResultSize' => 'setTotalResultSize',
        'notificationType' => 'setNotificationType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'typeOfChange' => 'getTypeOfChange',
        'operation' => 'getOperation',
        'employeeName' => 'getEmployeeName',
        'data' => 'getData',
        'totalResultSize' => 'getTotalResultSize',
        'notificationType' => 'getNotificationType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const NOTIFICATION_TYPE_COUPON_UPDATED = 'CouponUpdated';
    public const NOTIFICATION_TYPE_COUPON_DELETED = 'CouponDeleted';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNotificationTypeAllowableValues()
    {
        return [
            self::NOTIFICATION_TYPE_COUPON_UPDATED,
            self::NOTIFICATION_TYPE_COUPON_DELETED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('typeOfChange', $data ?? [], null);
        $this->setIfExists('operation', $data ?? [], null);
        $this->setIfExists('employeeName', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('totalResultSize', $data ?? [], null);
        $this->setIfExists('notificationType', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['typeOfChange'] === null) {
            $invalidProperties[] = "'typeOfChange' can't be null";
        }
        if ($this->container['operation'] === null) {
            $invalidProperties[] = "'operation' can't be null";
        }
        if ($this->container['employeeName'] === null) {
            $invalidProperties[] = "'employeeName' can't be null";
        }
        if ($this->container['notificationType'] === null) {
            $invalidProperties[] = "'notificationType' can't be null";
        }
        $allowedValues = $this->getNotificationTypeAllowableValues();
        if (!is_null($this->container['notificationType']) && !in_array($this->container['notificationType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'notificationType', must be one of '%s'",
                $this->container['notificationType'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets typeOfChange
     *
     * @return string
     */
    public function getTypeOfChange()
    {
        return $this->container['typeOfChange'];
    }

    /**
     * Sets typeOfChange
     *
     * @param string $typeOfChange The type of change that occurred.
     *
     * @return self
     */
    public function setTypeOfChange($typeOfChange)
    {
        if (is_null($typeOfChange)) {
            throw new \InvalidArgumentException('non-nullable typeOfChange cannot be null');
        }
        $this->container['typeOfChange'] = $typeOfChange;

        return $this;
    }

    /**
     * Gets operation
     *
     * @return string
     */
    public function getOperation()
    {
        return $this->container['operation'];
    }

    /**
     * Sets operation
     *
     * @param string $operation The operation performed.
     *
     * @return self
     */
    public function setOperation($operation)
    {
        if (is_null($operation)) {
            throw new \InvalidArgumentException('non-nullable operation cannot be null');
        }
        $this->container['operation'] = $operation;

        return $this;
    }

    /**
     * Gets employeeName
     *
     * @return string
     */
    public function getEmployeeName()
    {
        return $this->container['employeeName'];
    }

    /**
     * Sets employeeName
     *
     * @param string $employeeName The name of the employee associated with the operation.
     *
     * @return self
     */
    public function setEmployeeName($employeeName)
    {
        if (is_null($employeeName)) {
            throw new \InvalidArgumentException('non-nullable employeeName cannot be null');
        }
        $this->container['employeeName'] = $employeeName;

        return $this;
    }

    /**
     * Gets data
     *
     * @return \TalonOne\Client\Model\ExtendedCoupon[]|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \TalonOne\Client\Model\ExtendedCoupon[]|null $data A list of extended coupon data.
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            throw new \InvalidArgumentException('non-nullable data cannot be null');
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets totalResultSize
     *
     * @return int|null
     */
    public function getTotalResultSize()
    {
        return $this->container['totalResultSize'];
    }

    /**
     * Sets totalResultSize
     *
     * @param int|null $totalResultSize totalResultSize
     *
     * @return self
     */
    public function setTotalResultSize($totalResultSize)
    {
        if (is_null($totalResultSize)) {
            throw new \InvalidArgumentException('non-nullable totalResultSize cannot be null');
        }
        $this->container['totalResultSize'] = $totalResultSize;

        return $this;
    }

    /**
     * Gets notificationType
     *
     * @return string
     */
    public function getNotificationType()
    {
        return $this->container['notificationType'];
    }

    /**
     * Sets notificationType
     *
     * @param string $notificationType The type of the notification
     *
     * @return self
     */
    public function setNotificationType($notificationType)
    {
        if (is_null($notificationType)) {
            throw new \InvalidArgumentException('non-nullable notificationType cannot be null');
        }
        $allowedValues = $this->getNotificationTypeAllowableValues();
        if (!in_array($notificationType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'notificationType', must be one of '%s'",
                    $notificationType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['notificationType'] = $notificationType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


