<?php
/**
 * CustomerActivityReport
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * CustomerActivityReport Class Doc Comment
 *
 * @category Class
 * @description A summary report of customer activity for a given time range.
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomerActivityReport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomerActivityReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'integrationId' => 'string',
        'created' => '\DateTime',
        'name' => 'string',
        'customerId' => 'int',
        'lastActivity' => '\DateTime',
        'couponRedemptions' => 'int',
        'couponUseAttempts' => 'int',
        'couponFailedAttempts' => 'int',
        'accruedDiscounts' => 'float',
        'accruedRevenue' => 'float',
        'totalOrders' => 'int',
        'totalOrdersNoCoupon' => 'int',
        'campaignName' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'integrationId' => 'string',
        'created' => 'date-time',
        'name' => null,
        'customerId' => 'int64',
        'lastActivity' => 'date-time',
        'couponRedemptions' => 'int64',
        'couponUseAttempts' => 'int64',
        'couponFailedAttempts' => 'int64',
        'accruedDiscounts' => null,
        'accruedRevenue' => null,
        'totalOrders' => 'int64',
        'totalOrdersNoCoupon' => 'int64',
        'campaignName' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'integrationId' => false,
        'created' => false,
        'name' => false,
        'customerId' => false,
        'lastActivity' => false,
        'couponRedemptions' => false,
        'couponUseAttempts' => false,
        'couponFailedAttempts' => false,
        'accruedDiscounts' => false,
        'accruedRevenue' => false,
        'totalOrders' => false,
        'totalOrdersNoCoupon' => false,
        'campaignName' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'integrationId' => 'integrationId',
        'created' => 'created',
        'name' => 'name',
        'customerId' => 'customerId',
        'lastActivity' => 'lastActivity',
        'couponRedemptions' => 'couponRedemptions',
        'couponUseAttempts' => 'couponUseAttempts',
        'couponFailedAttempts' => 'couponFailedAttempts',
        'accruedDiscounts' => 'accruedDiscounts',
        'accruedRevenue' => 'accruedRevenue',
        'totalOrders' => 'totalOrders',
        'totalOrdersNoCoupon' => 'totalOrdersNoCoupon',
        'campaignName' => 'campaignName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'integrationId' => 'setIntegrationId',
        'created' => 'setCreated',
        'name' => 'setName',
        'customerId' => 'setCustomerId',
        'lastActivity' => 'setLastActivity',
        'couponRedemptions' => 'setCouponRedemptions',
        'couponUseAttempts' => 'setCouponUseAttempts',
        'couponFailedAttempts' => 'setCouponFailedAttempts',
        'accruedDiscounts' => 'setAccruedDiscounts',
        'accruedRevenue' => 'setAccruedRevenue',
        'totalOrders' => 'setTotalOrders',
        'totalOrdersNoCoupon' => 'setTotalOrdersNoCoupon',
        'campaignName' => 'setCampaignName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'integrationId' => 'getIntegrationId',
        'created' => 'getCreated',
        'name' => 'getName',
        'customerId' => 'getCustomerId',
        'lastActivity' => 'getLastActivity',
        'couponRedemptions' => 'getCouponRedemptions',
        'couponUseAttempts' => 'getCouponUseAttempts',
        'couponFailedAttempts' => 'getCouponFailedAttempts',
        'accruedDiscounts' => 'getAccruedDiscounts',
        'accruedRevenue' => 'getAccruedRevenue',
        'totalOrders' => 'getTotalOrders',
        'totalOrdersNoCoupon' => 'getTotalOrdersNoCoupon',
        'campaignName' => 'getCampaignName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('integrationId', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('lastActivity', $data ?? [], null);
        $this->setIfExists('couponRedemptions', $data ?? [], null);
        $this->setIfExists('couponUseAttempts', $data ?? [], null);
        $this->setIfExists('couponFailedAttempts', $data ?? [], null);
        $this->setIfExists('accruedDiscounts', $data ?? [], null);
        $this->setIfExists('accruedRevenue', $data ?? [], null);
        $this->setIfExists('totalOrders', $data ?? [], null);
        $this->setIfExists('totalOrdersNoCoupon', $data ?? [], null);
        $this->setIfExists('campaignName', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['integrationId'] === null) {
            $invalidProperties[] = "'integrationId' can't be null";
        }
        if ((mb_strlen($this->container['integrationId']) > 1000)) {
            $invalidProperties[] = "invalid value for 'integrationId', the character length must be smaller than or equal to 1000.";
        }

        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['customerId'] === null) {
            $invalidProperties[] = "'customerId' can't be null";
        }
        if ($this->container['couponRedemptions'] === null) {
            $invalidProperties[] = "'couponRedemptions' can't be null";
        }
        if ($this->container['couponUseAttempts'] === null) {
            $invalidProperties[] = "'couponUseAttempts' can't be null";
        }
        if ($this->container['couponFailedAttempts'] === null) {
            $invalidProperties[] = "'couponFailedAttempts' can't be null";
        }
        if ($this->container['accruedDiscounts'] === null) {
            $invalidProperties[] = "'accruedDiscounts' can't be null";
        }
        if ($this->container['accruedRevenue'] === null) {
            $invalidProperties[] = "'accruedRevenue' can't be null";
        }
        if ($this->container['totalOrders'] === null) {
            $invalidProperties[] = "'totalOrders' can't be null";
        }
        if ($this->container['totalOrdersNoCoupon'] === null) {
            $invalidProperties[] = "'totalOrdersNoCoupon' can't be null";
        }
        if ($this->container['campaignName'] === null) {
            $invalidProperties[] = "'campaignName' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets integrationId
     *
     * @return string
     */
    public function getIntegrationId()
    {
        return $this->container['integrationId'];
    }

    /**
     * Sets integrationId
     *
     * @param string $integrationId The integration ID set by your integration layer.
     *
     * @return self
     */
    public function setIntegrationId($integrationId)
    {
        if (is_null($integrationId)) {
            throw new \InvalidArgumentException('non-nullable integrationId cannot be null');
        }
        if ((mb_strlen($integrationId) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $integrationId when calling CustomerActivityReport., must be smaller than or equal to 1000.');
        }

        $this->container['integrationId'] = $integrationId;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created The time this entity was created.
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name for this customer profile.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return int
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param int $customerId The internal Talon.One ID of the customer.
     *
     * @return self
     */
    public function setCustomerId($customerId)
    {
        if (is_null($customerId)) {
            throw new \InvalidArgumentException('non-nullable customerId cannot be null');
        }
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets lastActivity
     *
     * @return \DateTime|null
     */
    public function getLastActivity()
    {
        return $this->container['lastActivity'];
    }

    /**
     * Sets lastActivity
     *
     * @param \DateTime|null $lastActivity The last activity of the customer.
     *
     * @return self
     */
    public function setLastActivity($lastActivity)
    {
        if (is_null($lastActivity)) {
            throw new \InvalidArgumentException('non-nullable lastActivity cannot be null');
        }
        $this->container['lastActivity'] = $lastActivity;

        return $this;
    }

    /**
     * Gets couponRedemptions
     *
     * @return int
     */
    public function getCouponRedemptions()
    {
        return $this->container['couponRedemptions'];
    }

    /**
     * Sets couponRedemptions
     *
     * @param int $couponRedemptions Number of coupon redemptions in all customer campaigns.
     *
     * @return self
     */
    public function setCouponRedemptions($couponRedemptions)
    {
        if (is_null($couponRedemptions)) {
            throw new \InvalidArgumentException('non-nullable couponRedemptions cannot be null');
        }
        $this->container['couponRedemptions'] = $couponRedemptions;

        return $this;
    }

    /**
     * Gets couponUseAttempts
     *
     * @return int
     */
    public function getCouponUseAttempts()
    {
        return $this->container['couponUseAttempts'];
    }

    /**
     * Sets couponUseAttempts
     *
     * @param int $couponUseAttempts Number of coupon use attempts in all customer campaigns.
     *
     * @return self
     */
    public function setCouponUseAttempts($couponUseAttempts)
    {
        if (is_null($couponUseAttempts)) {
            throw new \InvalidArgumentException('non-nullable couponUseAttempts cannot be null');
        }
        $this->container['couponUseAttempts'] = $couponUseAttempts;

        return $this;
    }

    /**
     * Gets couponFailedAttempts
     *
     * @return int
     */
    public function getCouponFailedAttempts()
    {
        return $this->container['couponFailedAttempts'];
    }

    /**
     * Sets couponFailedAttempts
     *
     * @param int $couponFailedAttempts Number of failed coupon use attempts in all customer campaigns.
     *
     * @return self
     */
    public function setCouponFailedAttempts($couponFailedAttempts)
    {
        if (is_null($couponFailedAttempts)) {
            throw new \InvalidArgumentException('non-nullable couponFailedAttempts cannot be null');
        }
        $this->container['couponFailedAttempts'] = $couponFailedAttempts;

        return $this;
    }

    /**
     * Gets accruedDiscounts
     *
     * @return float
     */
    public function getAccruedDiscounts()
    {
        return $this->container['accruedDiscounts'];
    }

    /**
     * Sets accruedDiscounts
     *
     * @param float $accruedDiscounts Number of accrued discounts in all customer campaigns.
     *
     * @return self
     */
    public function setAccruedDiscounts($accruedDiscounts)
    {
        if (is_null($accruedDiscounts)) {
            throw new \InvalidArgumentException('non-nullable accruedDiscounts cannot be null');
        }
        $this->container['accruedDiscounts'] = $accruedDiscounts;

        return $this;
    }

    /**
     * Gets accruedRevenue
     *
     * @return float
     */
    public function getAccruedRevenue()
    {
        return $this->container['accruedRevenue'];
    }

    /**
     * Sets accruedRevenue
     *
     * @param float $accruedRevenue Amount of accrued revenue in all customer campaigns.
     *
     * @return self
     */
    public function setAccruedRevenue($accruedRevenue)
    {
        if (is_null($accruedRevenue)) {
            throw new \InvalidArgumentException('non-nullable accruedRevenue cannot be null');
        }
        $this->container['accruedRevenue'] = $accruedRevenue;

        return $this;
    }

    /**
     * Gets totalOrders
     *
     * @return int
     */
    public function getTotalOrders()
    {
        return $this->container['totalOrders'];
    }

    /**
     * Sets totalOrders
     *
     * @param int $totalOrders Number of orders in all customer campaigns.
     *
     * @return self
     */
    public function setTotalOrders($totalOrders)
    {
        if (is_null($totalOrders)) {
            throw new \InvalidArgumentException('non-nullable totalOrders cannot be null');
        }
        $this->container['totalOrders'] = $totalOrders;

        return $this;
    }

    /**
     * Gets totalOrdersNoCoupon
     *
     * @return int
     */
    public function getTotalOrdersNoCoupon()
    {
        return $this->container['totalOrdersNoCoupon'];
    }

    /**
     * Sets totalOrdersNoCoupon
     *
     * @param int $totalOrdersNoCoupon Number of orders without coupon used in all customer campaigns.
     *
     * @return self
     */
    public function setTotalOrdersNoCoupon($totalOrdersNoCoupon)
    {
        if (is_null($totalOrdersNoCoupon)) {
            throw new \InvalidArgumentException('non-nullable totalOrdersNoCoupon cannot be null');
        }
        $this->container['totalOrdersNoCoupon'] = $totalOrdersNoCoupon;

        return $this;
    }

    /**
     * Gets campaignName
     *
     * @return string
     */
    public function getCampaignName()
    {
        return $this->container['campaignName'];
    }

    /**
     * Sets campaignName
     *
     * @param string $campaignName The name of the campaign this customer belongs to.
     *
     * @return self
     */
    public function setCampaignName($campaignName)
    {
        if (is_null($campaignName)) {
            throw new \InvalidArgumentException('non-nullable campaignName cannot be null');
        }
        $this->container['campaignName'] = $campaignName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


