<?php
/**
 * CustomerProfileIntegrationRequestV2
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * CustomerProfileIntegrationRequestV2 Class Doc Comment
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomerProfileIntegrationRequestV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomerProfileIntegrationRequestV2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attributes' => 'object',
        'evaluableCampaignIds' => 'int[]',
        'audiencesChanges' => '\TalonOne\Client\Model\ProfileAudiencesChanges',
        'responseContent' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attributes' => null,
        'evaluableCampaignIds' => 'int64',
        'audiencesChanges' => null,
        'responseContent' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attributes' => false,
        'evaluableCampaignIds' => false,
        'audiencesChanges' => false,
        'responseContent' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attributes' => 'attributes',
        'evaluableCampaignIds' => 'evaluableCampaignIds',
        'audiencesChanges' => 'audiencesChanges',
        'responseContent' => 'responseContent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attributes' => 'setAttributes',
        'evaluableCampaignIds' => 'setEvaluableCampaignIds',
        'audiencesChanges' => 'setAudiencesChanges',
        'responseContent' => 'setResponseContent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attributes' => 'getAttributes',
        'evaluableCampaignIds' => 'getEvaluableCampaignIds',
        'audiencesChanges' => 'getAudiencesChanges',
        'responseContent' => 'getResponseContent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RESPONSE_CONTENT_CUSTOMER_PROFILE = 'customerProfile';
    public const RESPONSE_CONTENT_TRIGGERED_CAMPAIGNS = 'triggeredCampaigns';
    public const RESPONSE_CONTENT_LOYALTY = 'loyalty';
    public const RESPONSE_CONTENT_EVENT = 'event';
    public const RESPONSE_CONTENT_AWARDED_GIVEAWAYS = 'awardedGiveaways';
    public const RESPONSE_CONTENT_RULE_FAILURE_REASONS = 'ruleFailureReasons';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getResponseContentAllowableValues()
    {
        return [
            self::RESPONSE_CONTENT_CUSTOMER_PROFILE,
            self::RESPONSE_CONTENT_TRIGGERED_CAMPAIGNS,
            self::RESPONSE_CONTENT_LOYALTY,
            self::RESPONSE_CONTENT_EVENT,
            self::RESPONSE_CONTENT_AWARDED_GIVEAWAYS,
            self::RESPONSE_CONTENT_RULE_FAILURE_REASONS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('evaluableCampaignIds', $data ?? [], null);
        $this->setIfExists('audiencesChanges', $data ?? [], null);
        $this->setIfExists('responseContent', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attributes
     *
     * @return object|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param object|null $attributes Arbitrary properties associated with this item.
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets evaluableCampaignIds
     *
     * @return int[]|null
     */
    public function getEvaluableCampaignIds()
    {
        return $this->container['evaluableCampaignIds'];
    }

    /**
     * Sets evaluableCampaignIds
     *
     * @param int[]|null $evaluableCampaignIds When using the `dry` query parameter, use this property to list the campaign to be evaluated by the Rule Engine.  These campaigns will be evaluated, even if they are disabled, allowing you to test specific campaigns before activating them.
     *
     * @return self
     */
    public function setEvaluableCampaignIds($evaluableCampaignIds)
    {
        if (is_null($evaluableCampaignIds)) {
            throw new \InvalidArgumentException('non-nullable evaluableCampaignIds cannot be null');
        }
        $this->container['evaluableCampaignIds'] = $evaluableCampaignIds;

        return $this;
    }

    /**
     * Gets audiencesChanges
     *
     * @return \TalonOne\Client\Model\ProfileAudiencesChanges|null
     */
    public function getAudiencesChanges()
    {
        return $this->container['audiencesChanges'];
    }

    /**
     * Sets audiencesChanges
     *
     * @param \TalonOne\Client\Model\ProfileAudiencesChanges|null $audiencesChanges Audiences memberships changes for this profile.
     *
     * @return self
     */
    public function setAudiencesChanges($audiencesChanges)
    {
        if (is_null($audiencesChanges)) {
            throw new \InvalidArgumentException('non-nullable audiencesChanges cannot be null');
        }
        $this->container['audiencesChanges'] = $audiencesChanges;

        return $this;
    }

    /**
     * Gets responseContent
     *
     * @return string[]|null
     */
    public function getResponseContent()
    {
        return $this->container['responseContent'];
    }

    /**
     * Sets responseContent
     *
     * @param string[]|null $responseContent Extends the response with the chosen data entities. Use this property to get as much data as you need in one _Update customer profile_ request instead of sending extra requests to other endpoints.
     *
     * @return self
     */
    public function setResponseContent($responseContent)
    {
        if (is_null($responseContent)) {
            throw new \InvalidArgumentException('non-nullable responseContent cannot be null');
        }
        $allowedValues = $this->getResponseContentAllowableValues();
        if (array_diff($responseContent, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'responseContent', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['responseContent'] = $responseContent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


