<?php
/**
 * NewCustomerSessionV2
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * NewCustomerSessionV2 Class Doc Comment
 *
 * @category Class
 * @description The representation of the customer session.
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NewCustomerSessionV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NewCustomerSessionV2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'profileId' => 'string',
        'storeIntegrationId' => 'string',
        'evaluableCampaignIds' => 'int[]',
        'couponCodes' => 'string[]',
        'referralCode' => 'string',
        'loyaltyCards' => 'string[]',
        'state' => 'string',
        'cartItems' => '\TalonOne\Client\Model\CartItem[]',
        'experimentVariantAllocations' => '\TalonOne\Client\Model\ExperimentVariantAllocation[]',
        'additionalCosts' => 'array<string,\TalonOne\Client\Model\AdditionalCost>',
        'identifiers' => 'string[]',
        'attributes' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'profileId' => null,
        'storeIntegrationId' => null,
        'evaluableCampaignIds' => 'int64',
        'couponCodes' => null,
        'referralCode' => null,
        'loyaltyCards' => null,
        'state' => null,
        'cartItems' => null,
        'experimentVariantAllocations' => null,
        'additionalCosts' => null,
        'identifiers' => null,
        'attributes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'profileId' => false,
        'storeIntegrationId' => false,
        'evaluableCampaignIds' => false,
        'couponCodes' => false,
        'referralCode' => false,
        'loyaltyCards' => false,
        'state' => false,
        'cartItems' => false,
        'experimentVariantAllocations' => false,
        'additionalCosts' => false,
        'identifiers' => false,
        'attributes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'profileId' => 'profileId',
        'storeIntegrationId' => 'storeIntegrationId',
        'evaluableCampaignIds' => 'evaluableCampaignIds',
        'couponCodes' => 'couponCodes',
        'referralCode' => 'referralCode',
        'loyaltyCards' => 'loyaltyCards',
        'state' => 'state',
        'cartItems' => 'cartItems',
        'experimentVariantAllocations' => 'experimentVariantAllocations',
        'additionalCosts' => 'additionalCosts',
        'identifiers' => 'identifiers',
        'attributes' => 'attributes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'profileId' => 'setProfileId',
        'storeIntegrationId' => 'setStoreIntegrationId',
        'evaluableCampaignIds' => 'setEvaluableCampaignIds',
        'couponCodes' => 'setCouponCodes',
        'referralCode' => 'setReferralCode',
        'loyaltyCards' => 'setLoyaltyCards',
        'state' => 'setState',
        'cartItems' => 'setCartItems',
        'experimentVariantAllocations' => 'setExperimentVariantAllocations',
        'additionalCosts' => 'setAdditionalCosts',
        'identifiers' => 'setIdentifiers',
        'attributes' => 'setAttributes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'profileId' => 'getProfileId',
        'storeIntegrationId' => 'getStoreIntegrationId',
        'evaluableCampaignIds' => 'getEvaluableCampaignIds',
        'couponCodes' => 'getCouponCodes',
        'referralCode' => 'getReferralCode',
        'loyaltyCards' => 'getLoyaltyCards',
        'state' => 'getState',
        'cartItems' => 'getCartItems',
        'experimentVariantAllocations' => 'getExperimentVariantAllocations',
        'additionalCosts' => 'getAdditionalCosts',
        'identifiers' => 'getIdentifiers',
        'attributes' => 'getAttributes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATE_OPEN = 'open';
    public const STATE_CLOSED = 'closed';
    public const STATE_PARTIALLY_RETURNED = 'partially_returned';
    public const STATE_CANCELLED = 'cancelled';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_OPEN,
            self::STATE_CLOSED,
            self::STATE_PARTIALLY_RETURNED,
            self::STATE_CANCELLED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('profileId', $data ?? [], null);
        $this->setIfExists('storeIntegrationId', $data ?? [], null);
        $this->setIfExists('evaluableCampaignIds', $data ?? [], null);
        $this->setIfExists('couponCodes', $data ?? [], null);
        $this->setIfExists('referralCode', $data ?? [], null);
        $this->setIfExists('loyaltyCards', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], 'open');
        $this->setIfExists('cartItems', $data ?? [], null);
        $this->setIfExists('experimentVariantAllocations', $data ?? [], null);
        $this->setIfExists('additionalCosts', $data ?? [], null);
        $this->setIfExists('identifiers', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['storeIntegrationId']) && (mb_strlen($this->container['storeIntegrationId']) > 1000)) {
            $invalidProperties[] = "invalid value for 'storeIntegrationId', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['storeIntegrationId']) && (mb_strlen($this->container['storeIntegrationId']) < 1)) {
            $invalidProperties[] = "invalid value for 'storeIntegrationId', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['referralCode']) && (mb_strlen($this->container['referralCode']) > 100)) {
            $invalidProperties[] = "invalid value for 'referralCode', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['loyaltyCards']) && (count($this->container['loyaltyCards']) > 1)) {
            $invalidProperties[] = "invalid value for 'loyaltyCards', number of items must be less than or equal to 1.";
        }

        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'state', must be one of '%s'",
                $this->container['state'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['identifiers']) && (count($this->container['identifiers']) > 5)) {
            $invalidProperties[] = "invalid value for 'identifiers', number of items must be less than or equal to 5.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets profileId
     *
     * @return string|null
     */
    public function getProfileId()
    {
        return $this->container['profileId'];
    }

    /**
     * Sets profileId
     *
     * @param string|null $profileId ID of the customer profile set by your integration layer.  **Note:** If the customer does not yet have a known `profileId`, we recommend you use a guest `profileId`.
     *
     * @return self
     */
    public function setProfileId($profileId)
    {
        if (is_null($profileId)) {
            throw new \InvalidArgumentException('non-nullable profileId cannot be null');
        }
        $this->container['profileId'] = $profileId;

        return $this;
    }

    /**
     * Gets storeIntegrationId
     *
     * @return string|null
     */
    public function getStoreIntegrationId()
    {
        return $this->container['storeIntegrationId'];
    }

    /**
     * Sets storeIntegrationId
     *
     * @param string|null $storeIntegrationId The integration ID of the store. You choose this ID when you create a store.
     *
     * @return self
     */
    public function setStoreIntegrationId($storeIntegrationId)
    {
        if (is_null($storeIntegrationId)) {
            throw new \InvalidArgumentException('non-nullable storeIntegrationId cannot be null');
        }
        if ((mb_strlen($storeIntegrationId) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $storeIntegrationId when calling NewCustomerSessionV2., must be smaller than or equal to 1000.');
        }
        if ((mb_strlen($storeIntegrationId) < 1)) {
            throw new \InvalidArgumentException('invalid length for $storeIntegrationId when calling NewCustomerSessionV2., must be bigger than or equal to 1.');
        }

        $this->container['storeIntegrationId'] = $storeIntegrationId;

        return $this;
    }

    /**
     * Gets evaluableCampaignIds
     *
     * @return int[]|null
     */
    public function getEvaluableCampaignIds()
    {
        return $this->container['evaluableCampaignIds'];
    }

    /**
     * Sets evaluableCampaignIds
     *
     * @param int[]|null $evaluableCampaignIds When using the `dry` query parameter, use this property to list the campaign to be evaluated by the Rule Engine.  These campaigns will be evaluated, even if they are disabled, allowing you to test specific campaigns before activating them.
     *
     * @return self
     */
    public function setEvaluableCampaignIds($evaluableCampaignIds)
    {
        if (is_null($evaluableCampaignIds)) {
            throw new \InvalidArgumentException('non-nullable evaluableCampaignIds cannot be null');
        }
        $this->container['evaluableCampaignIds'] = $evaluableCampaignIds;

        return $this;
    }

    /**
     * Gets couponCodes
     *
     * @return string[]|null
     */
    public function getCouponCodes()
    {
        return $this->container['couponCodes'];
    }

    /**
     * Sets couponCodes
     *
     * @param string[]|null $couponCodes Any coupon codes entered.  **Important - for requests only**:  - If you [create a coupon budget](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/#budget-types) for your campaign, ensure the session contains a coupon code by the time you close it. - In requests where `dry=false`, providing an empty array discards any previous coupons. To avoid this, omit the parameter entirely.
     *
     * @return self
     */
    public function setCouponCodes($couponCodes)
    {
        if (is_null($couponCodes)) {
            throw new \InvalidArgumentException('non-nullable couponCodes cannot be null');
        }
        $this->container['couponCodes'] = $couponCodes;

        return $this;
    }

    /**
     * Gets referralCode
     *
     * @return string|null
     */
    public function getReferralCode()
    {
        return $this->container['referralCode'];
    }

    /**
     * Sets referralCode
     *
     * @param string|null $referralCode Any referral code entered.  **Important - for requests only**:  - If you [create a referral budget](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/#budget-types) for your campaign, ensure the session contains a referral code by the time you close it. - In requests where `dry=false`, providing an empty value discards the previous referral code. To avoid this, omit the parameter entirely.
     *
     * @return self
     */
    public function setReferralCode($referralCode)
    {
        if (is_null($referralCode)) {
            throw new \InvalidArgumentException('non-nullable referralCode cannot be null');
        }
        if ((mb_strlen($referralCode) > 100)) {
            throw new \InvalidArgumentException('invalid length for $referralCode when calling NewCustomerSessionV2., must be smaller than or equal to 100.');
        }

        $this->container['referralCode'] = $referralCode;

        return $this;
    }

    /**
     * Gets loyaltyCards
     *
     * @return string[]|null
     */
    public function getLoyaltyCards()
    {
        return $this->container['loyaltyCards'];
    }

    /**
     * Sets loyaltyCards
     *
     * @param string[]|null $loyaltyCards Identifier of a loyalty card.
     *
     * @return self
     */
    public function setLoyaltyCards($loyaltyCards)
    {
        if (is_null($loyaltyCards)) {
            throw new \InvalidArgumentException('non-nullable loyaltyCards cannot be null');
        }

        if ((count($loyaltyCards) > 1)) {
            throw new \InvalidArgumentException('invalid value for $loyaltyCards when calling NewCustomerSessionV2., number of items must be less than or equal to 1.');
        }
        $this->container['loyaltyCards'] = $loyaltyCards;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state Indicates the current state of the session. Sessions can be created as `open` or `closed`. The state transitions are:  1. `open` → `closed` 2. `open` → `cancelled` 3. Either:    - `closed` → `cancelled` (**only** via [Update customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2)) or    - `closed` → `partially_returned` (**only** via [Return cart items](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/returnCartItems))    - `closed` → `open` (**only** via [Reopen customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/reopenCustomerSession)) 4. `partially_returned` → `cancelled`  For more information, see [Customer session states](https://docs.talon.one/docs/dev/concepts/entities/customer-sessions).
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!in_array($state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'state', must be one of '%s'",
                    $state,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets cartItems
     *
     * @return \TalonOne\Client\Model\CartItem[]|null
     */
    public function getCartItems()
    {
        return $this->container['cartItems'];
    }

    /**
     * Sets cartItems
     *
     * @param \TalonOne\Client\Model\CartItem[]|null $cartItems The items to add to this session. **Do not exceed 1000 items** and ensure the sum of all cart item's `quantity` **does not exceed 10.000** per request.
     *
     * @return self
     */
    public function setCartItems($cartItems)
    {
        if (is_null($cartItems)) {
            throw new \InvalidArgumentException('non-nullable cartItems cannot be null');
        }
        $this->container['cartItems'] = $cartItems;

        return $this;
    }

    /**
     * Gets experimentVariantAllocations
     *
     * @return \TalonOne\Client\Model\ExperimentVariantAllocation[]|null
     */
    public function getExperimentVariantAllocations()
    {
        return $this->container['experimentVariantAllocations'];
    }

    /**
     * Sets experimentVariantAllocations
     *
     * @param \TalonOne\Client\Model\ExperimentVariantAllocation[]|null $experimentVariantAllocations The experiment variant allocations to add to this session.
     *
     * @return self
     */
    public function setExperimentVariantAllocations($experimentVariantAllocations)
    {
        if (is_null($experimentVariantAllocations)) {
            throw new \InvalidArgumentException('non-nullable experimentVariantAllocations cannot be null');
        }
        $this->container['experimentVariantAllocations'] = $experimentVariantAllocations;

        return $this;
    }

    /**
     * Gets additionalCosts
     *
     * @return array<string,\TalonOne\Client\Model\AdditionalCost>|null
     */
    public function getAdditionalCosts()
    {
        return $this->container['additionalCosts'];
    }

    /**
     * Sets additionalCosts
     *
     * @param array<string,\TalonOne\Client\Model\AdditionalCost>|null $additionalCosts Use this property to set a value for the additional costs of this session, such as a shipping cost.  They must be created in the Campaign Manager before you set them with this property. See [Managing additional costs](https://docs.talon.one/docs/product/account/dev-tools/managing-additional-costs).
     *
     * @return self
     */
    public function setAdditionalCosts($additionalCosts)
    {
        if (is_null($additionalCosts)) {
            throw new \InvalidArgumentException('non-nullable additionalCosts cannot be null');
        }
        $this->container['additionalCosts'] = $additionalCosts;

        return $this;
    }

    /**
     * Gets identifiers
     *
     * @return string[]|null
     */
    public function getIdentifiers()
    {
        return $this->container['identifiers'];
    }

    /**
     * Sets identifiers
     *
     * @param string[]|null $identifiers Session custom identifiers that you can set limits on or use inside your rules.  For example, you can use IP addresses as identifiers to potentially identify devices and limit discounts abuse in case of customers creating multiple accounts. See the [tutorial](https://docs.talon.one/docs/dev/tutorials/using-identifiers).  **Important**: Ensure the session contains an identifier by the time you close it if: - You [create a unique identifier budget](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/#budget-types) for your campaign. - Your campaign has [coupons](https://docs.talon.one/docs/product/campaigns/coupons/coupon-page-overview). - We recommend passing an anonymized (hashed) version of the identifier value.
     *
     * @return self
     */
    public function setIdentifiers($identifiers)
    {
        if (is_null($identifiers)) {
            throw new \InvalidArgumentException('non-nullable identifiers cannot be null');
        }

        if ((count($identifiers) > 5)) {
            throw new \InvalidArgumentException('invalid value for $identifiers when calling NewCustomerSessionV2., number of items must be less than or equal to 5.');
        }
        $this->container['identifiers'] = $identifiers;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return object|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param object|null $attributes Use this property to set a value for the attributes of your choice. Attributes represent any information to attach to your session, like the shipping city.  You can use [built-in attributes](https://docs.talon.one/docs/dev/concepts/attributes#built-in-attributes) or [custom ones](https://docs.talon.one/docs/dev/concepts/attributes#custom-attributes). Custom attributes must be created in the Campaign Manager before you set them with this property.
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


