<?php
/**
 * StrikethroughEffect
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TalonOne\Client\Model;

use \ArrayAccess;
use \TalonOne\Client\ObjectSerializer;

/**
 * StrikethroughEffect Class Doc Comment
 *
 * @category Class
 * @description The effect produced for the catalog item.
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StrikethroughEffect implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StrikethroughEffect';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'campaignId' => 'int',
        'rulesetId' => 'int',
        'ruleIndex' => 'int',
        'ruleName' => 'string',
        'type' => 'string',
        'props' => 'object',
        'startTime' => '\DateTime',
        'endTime' => '\DateTime',
        'selectedPriceType' => 'string',
        'selectedPrice' => 'float',
        'adjustmentReferenceId' => 'string',
        'targets' => 'object[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'campaignId' => 'int64',
        'rulesetId' => 'int64',
        'ruleIndex' => 'int64',
        'ruleName' => null,
        'type' => null,
        'props' => null,
        'startTime' => 'date-time',
        'endTime' => 'date-time',
        'selectedPriceType' => null,
        'selectedPrice' => null,
        'adjustmentReferenceId' => null,
        'targets' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'campaignId' => false,
        'rulesetId' => false,
        'ruleIndex' => false,
        'ruleName' => false,
        'type' => false,
        'props' => false,
        'startTime' => false,
        'endTime' => false,
        'selectedPriceType' => false,
        'selectedPrice' => false,
        'adjustmentReferenceId' => false,
        'targets' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'campaignId' => 'campaignId',
        'rulesetId' => 'rulesetId',
        'ruleIndex' => 'ruleIndex',
        'ruleName' => 'ruleName',
        'type' => 'type',
        'props' => 'props',
        'startTime' => 'startTime',
        'endTime' => 'endTime',
        'selectedPriceType' => 'selectedPriceType',
        'selectedPrice' => 'selectedPrice',
        'adjustmentReferenceId' => 'adjustmentReferenceId',
        'targets' => 'targets'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'campaignId' => 'setCampaignId',
        'rulesetId' => 'setRulesetId',
        'ruleIndex' => 'setRuleIndex',
        'ruleName' => 'setRuleName',
        'type' => 'setType',
        'props' => 'setProps',
        'startTime' => 'setStartTime',
        'endTime' => 'setEndTime',
        'selectedPriceType' => 'setSelectedPriceType',
        'selectedPrice' => 'setSelectedPrice',
        'adjustmentReferenceId' => 'setAdjustmentReferenceId',
        'targets' => 'setTargets'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'campaignId' => 'getCampaignId',
        'rulesetId' => 'getRulesetId',
        'ruleIndex' => 'getRuleIndex',
        'ruleName' => 'getRuleName',
        'type' => 'getType',
        'props' => 'getProps',
        'startTime' => 'getStartTime',
        'endTime' => 'getEndTime',
        'selectedPriceType' => 'getSelectedPriceType',
        'selectedPrice' => 'getSelectedPrice',
        'adjustmentReferenceId' => 'getAdjustmentReferenceId',
        'targets' => 'getTargets'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('campaignId', $data ?? [], null);
        $this->setIfExists('rulesetId', $data ?? [], null);
        $this->setIfExists('ruleIndex', $data ?? [], null);
        $this->setIfExists('ruleName', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('props', $data ?? [], null);
        $this->setIfExists('startTime', $data ?? [], null);
        $this->setIfExists('endTime', $data ?? [], null);
        $this->setIfExists('selectedPriceType', $data ?? [], null);
        $this->setIfExists('selectedPrice', $data ?? [], null);
        $this->setIfExists('adjustmentReferenceId', $data ?? [], null);
        $this->setIfExists('targets', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['campaignId'] === null) {
            $invalidProperties[] = "'campaignId' can't be null";
        }
        if ($this->container['rulesetId'] === null) {
            $invalidProperties[] = "'rulesetId' can't be null";
        }
        if ($this->container['ruleIndex'] === null) {
            $invalidProperties[] = "'ruleIndex' can't be null";
        }
        if ($this->container['ruleName'] === null) {
            $invalidProperties[] = "'ruleName' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['props'] === null) {
            $invalidProperties[] = "'props' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets campaignId
     *
     * @return int
     */
    public function getCampaignId()
    {
        return $this->container['campaignId'];
    }

    /**
     * Sets campaignId
     *
     * @param int $campaignId The ID of the campaign that effect belongs to.
     *
     * @return self
     */
    public function setCampaignId($campaignId)
    {
        if (is_null($campaignId)) {
            throw new \InvalidArgumentException('non-nullable campaignId cannot be null');
        }
        $this->container['campaignId'] = $campaignId;

        return $this;
    }

    /**
     * Gets rulesetId
     *
     * @return int
     */
    public function getRulesetId()
    {
        return $this->container['rulesetId'];
    }

    /**
     * Sets rulesetId
     *
     * @param int $rulesetId The ID of the ruleset containing the rule that triggered this effect.
     *
     * @return self
     */
    public function setRulesetId($rulesetId)
    {
        if (is_null($rulesetId)) {
            throw new \InvalidArgumentException('non-nullable rulesetId cannot be null');
        }
        $this->container['rulesetId'] = $rulesetId;

        return $this;
    }

    /**
     * Gets ruleIndex
     *
     * @return int
     */
    public function getRuleIndex()
    {
        return $this->container['ruleIndex'];
    }

    /**
     * Sets ruleIndex
     *
     * @param int $ruleIndex The position of the rule that triggered this effect within the ruleset.
     *
     * @return self
     */
    public function setRuleIndex($ruleIndex)
    {
        if (is_null($ruleIndex)) {
            throw new \InvalidArgumentException('non-nullable ruleIndex cannot be null');
        }
        $this->container['ruleIndex'] = $ruleIndex;

        return $this;
    }

    /**
     * Gets ruleName
     *
     * @return string
     */
    public function getRuleName()
    {
        return $this->container['ruleName'];
    }

    /**
     * Sets ruleName
     *
     * @param string $ruleName The name of the rule that triggered this effect.
     *
     * @return self
     */
    public function setRuleName($ruleName)
    {
        if (is_null($ruleName)) {
            throw new \InvalidArgumentException('non-nullable ruleName cannot be null');
        }
        $this->container['ruleName'] = $ruleName;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The type of this effect.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets props
     *
     * @return object
     */
    public function getProps()
    {
        return $this->container['props'];
    }

    /**
     * Sets props
     *
     * @param object $props Arbitrary properties associated with this effect type.
     *
     * @return self
     */
    public function setProps($props)
    {
        if (is_null($props)) {
            throw new \InvalidArgumentException('non-nullable props cannot be null');
        }
        $this->container['props'] = $props;

        return $this;
    }

    /**
     * Gets startTime
     *
     * @return \DateTime|null
     */
    public function getStartTime()
    {
        return $this->container['startTime'];
    }

    /**
     * Sets startTime
     *
     * @param \DateTime|null $startTime The start of the time frame where the effect is active in UTC.
     *
     * @return self
     */
    public function setStartTime($startTime)
    {
        if (is_null($startTime)) {
            throw new \InvalidArgumentException('non-nullable startTime cannot be null');
        }
        $this->container['startTime'] = $startTime;

        return $this;
    }

    /**
     * Gets endTime
     *
     * @return \DateTime|null
     */
    public function getEndTime()
    {
        return $this->container['endTime'];
    }

    /**
     * Sets endTime
     *
     * @param \DateTime|null $endTime The end of the time frame where the effect is active in UTC.
     *
     * @return self
     */
    public function setEndTime($endTime)
    {
        if (is_null($endTime)) {
            throw new \InvalidArgumentException('non-nullable endTime cannot be null');
        }
        $this->container['endTime'] = $endTime;

        return $this;
    }

    /**
     * Gets selectedPriceType
     *
     * @return string|null
     */
    public function getSelectedPriceType()
    {
        return $this->container['selectedPriceType'];
    }

    /**
     * Sets selectedPriceType
     *
     * @param string|null $selectedPriceType The selected price type for this cart item (e.g. the price for members only).
     *
     * @return self
     */
    public function setSelectedPriceType($selectedPriceType)
    {
        if (is_null($selectedPriceType)) {
            throw new \InvalidArgumentException('non-nullable selectedPriceType cannot be null');
        }
        $this->container['selectedPriceType'] = $selectedPriceType;

        return $this;
    }

    /**
     * Gets selectedPrice
     *
     * @return float|null
     */
    public function getSelectedPrice()
    {
        return $this->container['selectedPrice'];
    }

    /**
     * Sets selectedPrice
     *
     * @param float|null $selectedPrice The value of the selected price type to apply to the SKU targeted by this effect, before any discounts are applied.
     *
     * @return self
     */
    public function setSelectedPrice($selectedPrice)
    {
        if (is_null($selectedPrice)) {
            throw new \InvalidArgumentException('non-nullable selectedPrice cannot be null');
        }
        $this->container['selectedPrice'] = $selectedPrice;

        return $this;
    }

    /**
     * Gets adjustmentReferenceId
     *
     * @return string|null
     */
    public function getAdjustmentReferenceId()
    {
        return $this->container['adjustmentReferenceId'];
    }

    /**
     * Sets adjustmentReferenceId
     *
     * @param string|null $adjustmentReferenceId The reference identifier of the selected price adjustment for this cart item.
     *
     * @return self
     */
    public function setAdjustmentReferenceId($adjustmentReferenceId)
    {
        if (is_null($adjustmentReferenceId)) {
            throw new \InvalidArgumentException('non-nullable adjustmentReferenceId cannot be null');
        }
        $this->container['adjustmentReferenceId'] = $adjustmentReferenceId;

        return $this;
    }

    /**
     * Gets targets
     *
     * @return object[]|null
     */
    public function getTargets()
    {
        return $this->container['targets'];
    }

    /**
     * Sets targets
     *
     * @param object[]|null $targets A list of entities (e.g. audiences) targeted by this effect.
     *
     * @return self
     */
    public function setTargets($targets)
    {
        if (is_null($targets)) {
            throw new \InvalidArgumentException('non-nullable targets cannot be null');
        }
        $this->container['targets'] = $targets;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


